In [1]:
import numpy as np
arr = np.array([[4.3,5],[1,2]])
arr1 = np.array([[3,2],[1,2]])
arr2= np.array([3,3,5])
print(type(arr))

<class 'numpy.ndarray'>


In [2]:
print(arr.ndim)

2


In [3]:
print(arr.size)

4


In [4]:
print(arr.dtype)

float64


In [5]:
print(arr.itemsize)

8


In [6]:
print(arr//arr1)

[[1. 2.]
 [1. 1.]]


In [7]:
print(np.sum([arr,arr1]))

20.3


In [8]:
print(np.cumsum(arr1))    #cum- add the current elemnt with total prevoious sum

[3 5 6 8]


In [9]:
print(np.add(arr,arr1))

[[7.3 7. ]
 [2.  4. ]]


In [10]:
print(np.subtract(arr,arr1))

[[1.3 3. ]
 [0.  0. ]]


In [11]:
print(np.mod(arr,arr1))

[[1.3 1. ]
 [0.  0. ]]


In [12]:
print(arr%arr1)

[[1.3 1. ]
 [0.  0. ]]


In [13]:
arr = np.array([[4,5],[1,2]])
arr1 = np.array([[2,3],[1,2]])
arr5=np.divmod(arr,arr1)
print(arr5)
print(type(arr5))

(array([[2, 1],
       [1, 1]]), array([[0, 2],
       [0, 0]]))
<class 'tuple'>


In [14]:
print(np.power(arr,arr1))

[[ 16 125]
 [  1   4]]


In [15]:
print(np.sin(np.pi/2))


1.0


In [16]:
print(np.deg2rad(90))

1.5707963267948966


In [17]:
print(arr.size)

4


In [18]:
from numpy import random
val = random.rand()
print(val)

0.3519628431446268


In [19]:
from numpy import random
val = random.randint(100)
print(val)

59


In [20]:
val2 = random.choice([-1,-22,-3,4,56,7,78,8,8])
print(val2)

-1


In [21]:
arr3=np.arange(10,20,2)
print(arr3)

[10 12 14 16 18]


In [22]:
arr3=np.arange(10,20).reshape(5,2)
print(arr3)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [23]:
arr3=np.arange(10,22,2).reshape(2,3)
print(arr3)

[[10 12 14]
 [16 18 20]]


In [24]:
random.shuffle(arr3)
print(arr3)

[[16 18 20]
 [10 12 14]]


In [29]:
import numpy as np
from numpy import random
val1=int(input("Enter the range : "))
val = random.randint(val1)
count=0
while True:
    count+=1
    x=int(input(f"Guess a number from 0-{val1}: "))
    if(val==x):
        print(f"Congrats!!! You guessed the number correctly on {count} tries. ")
        break
    elif(val>x):
        print("Try with greater number ")
    elif(val<x):   
        print("Try with Smaller number")
    

Enter the range : 2
Guess a number from 0-2: 1
Congrats!!! You guessed the number correctly on 1 tries. 


import numpy as np
from numpy import random
min=int(input("enter "))
max=int(input("enter "))
min1=((10**min)-1)
max1=((10**max)-1)
print(min1,max1)
count=0
x=int(input("pasword "))
while (1):
    count+=1
    val = random.randint(min1,max1)
    if(x==val):
        print(f"Congrats!!! {count} tries. ")
        break
        

## 