In [28]:
import numpy as np
arr = np.array([[4,5],[1,2]])
arr1 = np.array([[2,3],[1,2]])
arr2= np.array([3,3,5])
print(type(arr))

<class 'numpy.ndarray'>


In [29]:
print(arr.ndim)

2


In [30]:
print(arr.size)

4


In [31]:
print(arr.dtype)

int32


In [32]:
print(arr.itemsize)

4


In [33]:
print(arr//arr1)

[[2 1]
 [1 1]]


In [34]:
print(np.sum([arr,arr1]))

20


In [35]:
print(np.cumsum(arr1))    #cum- add the current elemnt with total prevoious sum

[2 5 6 8]


In [36]:
print(np.add(arr,arr1))

[[6 8]
 [2 4]]


In [37]:
print(np.subtract(arr,arr1))

[[2 2]
 [0 0]]


In [38]:
print(np.mod(arr,arr1))

[[0 2]
 [0 0]]


In [39]:
print(arr%arr1)

[[0 2]
 [0 0]]


In [41]:
arr = np.array([[4,5],[1,2]])
arr1 = np.array([[2,3],[1,2]])
arr5=np.divmod(arr,arr1)
print(arr5)
print(type(arr5))

(array([[2, 1],
       [1, 1]]), array([[0, 2],
       [0, 0]]))
<class 'tuple'>


In [42]:
print(arr.size)

4
